# Generated by Django 5.0.2 on 2024-02-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
