# Generated by Django 5.0.2 on 2024-02-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0005_todo_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date",
            field=models.DateField(),
        ),
    ]
