# Generated by Django 5.0.2 on 2024-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0006_alter_todo_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="time",
            field=models.TimeField(default="00:00"),
        ),
    ]
