# Generated by Django 5.0.2 on 2024-02-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0007_todo_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[("1", "🟥 High"), ("2", "🟧 Medium"), ("3", "🟩 Low")],
                max_length=2,
            ),
        ),
    ]
